name: Question
description: Ask a question about the project
title: "[QUESTION] "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help! Please provide as much context as possible.

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: Ask your question here...
    validations:
      required: true

  - type: dropdown
    id: question-category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Installation and setup
        - API usage
        - Diagram validation
        - Error troubleshooting
        - Performance
        - Configuration
        - Deployment
        - Contributing
        - Architecture/Design
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context for your question
      placeholder: |
        - What are you trying to accomplish?
        - What have you already tried?
        - Any relevant code or configuration?

  - type: textarea
    id: documentation-check
    attributes:
      label: Documentation Review
      description: Have you checked the existing documentation?
      placeholder: |
        Please let us know which documentation you've already reviewed:
        - [ ] README.md
        - [ ] GETTING_STARTED.md
        - [ ] API documentation at /docs
        - [ ] Other documentation files

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other details that might help us answer your question
      placeholder: Any additional context...