apiVersion: apps/v1
kind: Deployment
metadata:
  name: mermaid-validator-mcp
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: mermaid-validator-mcp
        env:
        - name: NODE_ENV
          value: "development"
        - name: LOG_LEVEL
          value: "debug"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi